### ISSUE TITLE
Lexing Error 발생

### ISSUE THREAD

**Issue by Kim-Gayoung** [kwanghoon/MySmallBasic#90]
regressiontest/ShapesTest.sb를 실행했을 경우 다음과 같은 에러가 발생합니다.

Exception in thread "main" com.coducation.smallbasic.LexerException: Line 1 : Char 1 : Lexing Error.
	at com.coducation.smallbasic.LexerAnalyzer.Lexing(LexerAnalyzer.java:347)
	at com.coducation.smallbasic.Parser.<init>(Parser.java:18)
	at com.coducation.smallbasic.MySmallBasicMain.main(MySmallBasicMain.java:24)

ShapesTest.sb의 첫번째 라인은 ﻿first = Shapes.AddRectangle(200, 20) 입니다.

**Comment by kwanghoon** [comment]
@KimGa-Young 
정확한 이유는 모르겠지만, Microsoft SmallBasic에서도 똑같은 에러가 발생한다.
더 확인해볼께.
👍

**Comment by kwanghoon** [comment]
@KimGa-Young 
에러가 나지 않는 버전으로 다시 올려놓았으니 필요한 부분을 수정하고 테스트해봐라.
